### ISSUE TITLE
Complete retext-equality entries

### ISSUE THREAD

**Issue by jdkato** [errata-ai/alex#1]
We still need most of the `or` cases:

https://github.com/retextjs/retext-equality/blob/7cd9ac532eb980f23ae8c59bbb1c662ee2701dea/data/en/gender.yml#L1301

An example implementation is:

```yaml
---
extends: sequence
message: "'%[1]s' may be insensitive, when referring to a person, use 'kid', 'child', or 'youth' instead."
ignorecase: true
level: warning
tokens:
  - pattern: boy|girl
    skip: 1

  - pattern: boy|girl
    negate: true
```
